package com.subtranslate.util

/**
 * Full list of languages supported by Google Translate (as of 2025).
 * Used in TranslateScreen and SettingsScreen target-language dropdowns.
 * Format: BCP-47 code → "🏳 Display Name"
 */
val GOOGLE_TRANSLATE_LANGUAGES: List<Pair<String, String>> = listOf(
    // ── Most common first ──────────────────────────────────────────────────
    "en"     to "🇺🇸 English",
    "he"     to "🇮🇱 Hebrew",
    "ar"     to "🇸🇦 Arabic",
    "fr"     to "🇫🇷 French",
    "de"     to "🇩🇪 German",
    "es"     to "🇪🇸 Spanish",
    "ru"     to "🇷🇺 Russian",
    "zh-CN"  to "🇨🇳 Chinese (Simplified)",
    "zh-TW"  to "🇹🇼 Chinese (Traditional)",
    "ja"     to "🇯🇵 Japanese",
    "ko"     to "🇰🇷 Korean",
    "pt"     to "🇵🇹 Portuguese",
    "it"     to "🇮🇹 Italian",
    "tr"     to "🇹🇷 Turkish",
    "nl"     to "🇳🇱 Dutch",
    "pl"     to "🇵🇱 Polish",
    "uk"     to "🇺🇦 Ukrainian",
    "fa"     to "🇮🇷 Persian",
    "hi"     to "🇮🇳 Hindi",
    "id"     to "🇮🇩 Indonesian",
    "vi"     to "🇻🇳 Vietnamese",
    "th"     to "🇹🇭 Thai",
    "sv"     to "🇸🇪 Swedish",
    "no"     to "🇳🇴 Norwegian",
    "da"     to "🇩🇰 Danish",
    "fi"     to "🇫🇮 Finnish",
    "ro"     to "🇷🇴 Romanian",
    "cs"     to "🇨🇿 Czech",
    "hu"     to "🇭🇺 Hungarian",
    "el"     to "🇬🇷 Greek",
    // ── Rest A-Z ───────────────────────────────────────────────────────────
    "af"     to "🇿🇦 Afrikaans",
    "sq"     to "🇦🇱 Albanian",
    "am"     to "🇪🇹 Amharic",
    "hy"     to "🇦🇲 Armenian",
    "as"     to "🇮🇳 Assamese",
    "ay"     to "🇧🇴 Aymara",
    "az"     to "🇦🇿 Azerbaijani",
    "bm"     to "🇲🇱 Bambara",
    "eu"     to "🏴 Basque",
    "be"     to "🇧🇾 Belarusian",
    "bn"     to "🇧🇩 Bengali",
    "bho"    to "🇮🇳 Bhojpuri",
    "bs"     to "🇧🇦 Bosnian",
    "bg"     to "🇧🇬 Bulgarian",
    "ca"     to "🏴 Catalan",
    "ceb"    to "🇵🇭 Cebuano",
    "co"     to "🇫🇷 Corsican",
    "hr"     to "🇭🇷 Croatian",
    "dv"     to "🇲🇻 Dhivehi",
    "doi"    to "🇮🇳 Dogri",
    "eo"     to "🌍 Esperanto",
    "et"     to "🇪🇪 Estonian",
    "ee"     to "🇬🇭 Ewe",
    "fil"    to "🇵🇭 Filipino",
    "fy"     to "🇳🇱 Frisian",
    "gl"     to "🇪🇸 Galician",
    "ka"     to "🇬🇪 Georgian",
    "gn"     to "🇵🇾 Guarani",
    "gu"     to "🇮🇳 Gujarati",
    "ht"     to "🇭🇹 Haitian Creole",
    "ha"     to "🇳🇬 Hausa",
    "haw"    to "🇺🇸 Hawaiian",
    "hmn"    to "🇱🇦 Hmong",
    "is"     to "🇮🇸 Icelandic",
    "ig"     to "🇳🇬 Igbo",
    "ilo"    to "🇵🇭 Ilocano",
    "ga"     to "🇮🇪 Irish",
    "jv"     to "🇮🇩 Javanese",
    "kn"     to "🇮🇳 Kannada",
    "kk"     to "🇰🇿 Kazakh",
    "km"     to "🇰🇭 Khmer",
    "rw"     to "🇷🇼 Kinyarwanda",
    "gom"    to "🇮🇳 Konkani",
    "kri"    to "🇸🇱 Krio",
    "ku"     to "🏴 Kurdish (Kurmanji)",
    "ckb"    to "🏴 Kurdish (Sorani)",
    "ky"     to "🇰🇬 Kyrgyz",
    "lo"     to "🇱🇦 Lao",
    "la"     to "🏛️ Latin",
    "lv"     to "🇱🇻 Latvian",
    "ln"     to "🇨🇩 Lingala",
    "lt"     to "🇱🇹 Lithuanian",
    "lg"     to "🇺🇬 Luganda",
    "lb"     to "🇱🇺 Luxembourgish",
    "mk"     to "🇲🇰 Macedonian",
    "mai"    to "🇮🇳 Maithili",
    "mg"     to "🇲🇬 Malagasy",
    "ms"     to "🇲🇾 Malay",
    "ml"     to "🇮🇳 Malayalam",
    "mt"     to "🇲🇹 Maltese",
    "mi"     to "🇳🇿 Maori",
    "mr"     to "🇮🇳 Marathi",
    "lus"    to "🇮🇳 Mizo",
    "mn"     to "🇲🇳 Mongolian",
    "my"     to "🇲🇲 Myanmar (Burmese)",
    "ne"     to "🇳🇵 Nepali",
    "ny"     to "🇲🇼 Nyanja (Chichewa)",
    "or"     to "🇮🇳 Odia (Oriya)",
    "om"     to "🇪🇹 Oromo",
    "ps"     to "🇦🇫 Pashto",
    "pa"     to "🇮🇳 Punjabi",
    "qu"     to "🇵🇪 Quechua",
    "sm"     to "🇼🇸 Samoan",
    "sa"     to "🇮🇳 Sanskrit",
    "gd"     to "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scots Gaelic",
    "nso"    to "🇿🇦 Sepedi",
    "sr"     to "🇷🇸 Serbian",
    "st"     to "🇱🇸 Sesotho",
    "sn"     to "🇿🇼 Shona",
    "sd"     to "🇵🇰 Sindhi",
    "si"     to "🇱🇰 Sinhala",
    "sk"     to "🇸🇰 Slovak",
    "sl"     to "🇸🇮 Slovenian",
    "so"     to "🇸🇴 Somali",
    "su"     to "🇮🇩 Sundanese",
    "sw"     to "🇰🇪 Swahili",
    "tl"     to "🇵🇭 Tagalog",
    "tg"     to "🇹🇯 Tajik",
    "ta"     to "🇮🇳 Tamil",
    "tt"     to "🇷🇺 Tatar",
    "te"     to "🇮🇳 Telugu",
    "ti"     to "🇪🇷 Tigrinya",
    "ts"     to "🇿🇦 Tsonga",
    "tk"     to "🇹🇲 Turkmen",
    "ak"     to "🇬🇭 Twi (Akan)",
    "ur"     to "🇵🇰 Urdu",
    "ug"     to "🇨🇳 Uyghur",
    "uz"     to "🇺🇿 Uzbek",
    "cy"     to "🏴󠁧󠁢󠁷󠁬󠁳󠁿 Welsh",
    "xh"     to "🇿🇦 Xhosa",
    "yi"     to "🕍 Yiddish",
    "yo"     to "🇳🇬 Yoruba",
    "zu"     to "🇿🇦 Zulu"
)

/**
 * Language codes for the subtitle-search language filter chips (OpenSubtitles codes).
 * These are the most commonly available subtitle languages on OpenSubtitles.
 */
val OPENSUBTITLES_SEARCH_LANGUAGES: List<Pair<String, String>> = listOf(
    "en"    to "🇺🇸 English",
    "he"    to "🇮🇱 Hebrew",
    "ar"    to "🇸🇦 Arabic",
    "fr"    to "🇫🇷 French",
    "de"    to "🇩🇪 German",
    "es"    to "🇪🇸 Spanish",
    "ru"    to "🇷🇺 Russian",
    "zh-cn" to "🇨🇳 Chinese (S)",
    "zh-tw" to "🇹🇼 Chinese (T)",
    "ja"    to "🇯🇵 Japanese",
    "ko"    to "🇰🇷 Korean",
    "pt"    to "🇵🇹 Portuguese",
    "pt-br" to "🇧🇷 Portuguese (BR)",
    "it"    to "🇮🇹 Italian",
    "tr"    to "🇹🇷 Turkish",
    "nl"    to "🇳🇱 Dutch",
    "pl"    to "🇵🇱 Polish",
    "uk"    to "🇺🇦 Ukrainian",
    "fa"    to "🇮🇷 Persian",
    "hi"    to "🇮🇳 Hindi",
    "id"    to "🇮🇩 Indonesian",
    "vi"    to "🇻🇳 Vietnamese",
    "th"    to "🇹🇭 Thai",
    "sv"    to "🇸🇪 Swedish",
    "no"    to "🇳🇴 Norwegian",
    "da"    to "🇩🇰 Danish",
    "fi"    to "🇫🇮 Finnish",
    "ro"    to "🇷🇴 Romanian",
    "cs"    to "🇨🇿 Czech",
    "hu"    to "🇭🇺 Hungarian",
    "el"    to "🇬🇷 Greek",
    "bg"    to "🇧🇬 Bulgarian",
    "hr"    to "🇭🇷 Croatian",
    "sk"    to "🇸🇰 Slovak",
    "sr"    to "🇷🇸 Serbian",
    "sl"    to "🇸🇮 Slovenian",
    "ca"    to "🏴 Catalan",
    "ms"    to "🇲🇾 Malay",
    "bn"    to "🇧🇩 Bengali",
    "ta"    to "🇮🇳 Tamil",
    "ml"    to "🇮🇳 Malayalam"
)
