package com.subtranslate.util

/**
 * Full list of languages supported by Google Translate (as of 2025).
 * Used in TranslateScreen and SettingsScreen target-language dropdowns.
 * Format: BCP-47 code → display name
 */
val GOOGLE_TRANSLATE_LANGUAGES: List<Pair<String, String>> = listOf(
    // ── Most common first ──────────────────────────────────────────────────
    "en"     to "English",
    "he"     to "Hebrew / עברית",
    "ar"     to "Arabic / العربية",
    "fr"     to "French / Français",
    "de"     to "German / Deutsch",
    "es"     to "Spanish / Español",
    "ru"     to "Russian / Русский",
    "zh-CN"  to "Chinese Simplified / 中文(简体)",
    "zh-TW"  to "Chinese Traditional / 中文(繁體)",
    "ja"     to "Japanese / 日本語",
    "ko"     to "Korean / 한국어",
    "pt"     to "Portuguese / Português",
    "it"     to "Italian / Italiano",
    "tr"     to "Turkish / Türkçe",
    "nl"     to "Dutch / Nederlands",
    "pl"     to "Polish / Polski",
    "uk"     to "Ukrainian / Українська",
    "fa"     to "Persian / فارسی",
    "hi"     to "Hindi / हिन्दी",
    "id"     to "Indonesian",
    "vi"     to "Vietnamese / Tiếng Việt",
    "th"     to "Thai / ภาษาไทย",
    "sv"     to "Swedish / Svenska",
    "no"     to "Norwegian / Norsk",
    "da"     to "Danish / Dansk",
    "fi"     to "Finnish / Suomi",
    "ro"     to "Romanian / Română",
    "cs"     to "Czech / Čeština",
    "hu"     to "Hungarian / Magyar",
    "el"     to "Greek / Ελληνικά",
    // ── Rest A-Z ───────────────────────────────────────────────────────────
    "af"     to "Afrikaans",
    "sq"     to "Albanian / Shqip",
    "am"     to "Amharic / አማርኛ",
    "hy"     to "Armenian / Հայերեն",
    "as"     to "Assamese / অসমীয়া",
    "ay"     to "Aymara",
    "az"     to "Azerbaijani / Azərbaycan",
    "bm"     to "Bambara",
    "eu"     to "Basque / Euskara",
    "be"     to "Belarusian / Беларуская",
    "bn"     to "Bengali / বাংলা",
    "bho"    to "Bhojpuri / भोजपुरी",
    "bs"     to "Bosnian / Bosanski",
    "bg"     to "Bulgarian / Български",
    "ca"     to "Catalan / Català",
    "ceb"    to "Cebuano",
    "co"     to "Corsican / Corsu",
    "hr"     to "Croatian / Hrvatski",
    "dv"     to "Dhivehi / ދިވެހި",
    "doi"    to "Dogri / डोगरी",
    "eo"     to "Esperanto",
    "et"     to "Estonian / Eesti",
    "ee"     to "Ewe / Eʋegbe",
    "fil"    to "Filipino / Tagalog",
    "fy"     to "Frisian / Frysk",
    "gl"     to "Galician / Galego",
    "ka"     to "Georgian / ქართული",
    "gn"     to "Guarani / Avañe'ẽ",
    "gu"     to "Gujarati / ગુજરાતી",
    "ht"     to "Haitian Creole / Kreyòl ayisyen",
    "ha"     to "Hausa / هَوُسَ",
    "haw"    to "Hawaiian / ʻŌlelo Hawaiʻi",
    "hmn"    to "Hmong / Hmoob",
    "is"     to "Icelandic / Íslenska",
    "ig"     to "Igbo / Asụsụ Igbo",
    "ilo"    to "Ilocano / Ilokano",
    "ga"     to "Irish / Gaeilge",
    "jv"     to "Javanese / Basa Jawa",
    "kn"     to "Kannada / ಕನ್ನಡ",
    "kk"     to "Kazakh / Қазақ",
    "km"     to "Khmer / ខ្មែរ",
    "rw"     to "Kinyarwanda",
    "gom"    to "Konkani / कोंकणी",
    "kri"    to "Krio",
    "ku"     to "Kurdish (Kurmanji) / Kurmancî",
    "ckb"    to "Kurdish (Sorani) / سۆرانی",
    "ky"     to "Kyrgyz / Кыргызча",
    "lo"     to "Lao / ພາສາລາວ",
    "la"     to "Latin / Latina",
    "lv"     to "Latvian / Latviešu",
    "ln"     to "Lingala",
    "lt"     to "Lithuanian / Lietuvių",
    "lg"     to "Luganda / Ganda",
    "lb"     to "Luxembourgish / Lëtzebuergesch",
    "mk"     to "Macedonian / Македонски",
    "mai"    to "Maithili / मैथिली",
    "mg"     to "Malagasy",
    "ms"     to "Malay / Bahasa Melayu",
    "ml"     to "Malayalam / മലയാളം",
    "mt"     to "Maltese / Malti",
    "mi"     to "Maori / Te Reo Māori",
    "mr"     to "Marathi / मराठी",
    "lus"    to "Mizo",
    "mn"     to "Mongolian / Монгол",
    "my"     to "Myanmar (Burmese) / မြန်မာ",
    "ne"     to "Nepali / नेपाली",
    "ny"     to "Nyanja (Chichewa)",
    "or"     to "Odia (Oriya) / ଓଡ଼ିଆ",
    "om"     to "Oromo / Afaan Oromoo",
    "ps"     to "Pashto / پښتو",
    "pa"     to "Punjabi / ਪੰਜਾਬੀ",
    "qu"     to "Quechua / Runasimi",
    "sm"     to "Samoan / Gagana Samoa",
    "sa"     to "Sanskrit / संस्कृत",
    "gd"     to "Scots Gaelic / Gàidhlig",
    "nso"    to "Sepedi / Sesotho sa Leboa",
    "sr"     to "Serbian / Српски",
    "st"     to "Sesotho / Sotho",
    "sn"     to "Shona / ChiShona",
    "sd"     to "Sindhi / سنڌي",
    "si"     to "Sinhala / සිංහල",
    "sk"     to "Slovak / Slovenčina",
    "sl"     to "Slovenian / Slovenščina",
    "so"     to "Somali / Soomaali",
    "su"     to "Sundanese / Basa Sunda",
    "sw"     to "Swahili / Kiswahili",
    "tl"     to "Tagalog",
    "tg"     to "Tajik / Тоҷикӣ",
    "ta"     to "Tamil / தமிழ்",
    "tt"     to "Tatar / Татар",
    "te"     to "Telugu / తెలుగు",
    "ti"     to "Tigrinya / ትግርኛ",
    "ts"     to "Tsonga / Xitsonga",
    "tk"     to "Turkmen / Türkmen",
    "ak"     to "Twi (Akan)",
    "ur"     to "Urdu / اردو",
    "ug"     to "Uyghur / ئۇيغۇرچە",
    "uz"     to "Uzbek / O'zbek",
    "cy"     to "Welsh / Cymraeg",
    "xh"     to "Xhosa / isiXhosa",
    "yi"     to "Yiddish / ייִדיש",
    "yo"     to "Yoruba / Yorùbá",
    "zu"     to "Zulu / isiZulu"
)

/**
 * Language codes for the subtitle-search language filter chips (OpenSubtitles codes).
 * These are the most commonly available subtitle languages on OpenSubtitles.
 */
val OPENSUBTITLES_SEARCH_LANGUAGES: List<Pair<String, String>> = listOf(
    "en"    to "English",
    "he"    to "עברית",
    "ar"    to "العربية",
    "fr"    to "Français",
    "de"    to "Deutsch",
    "es"    to "Español",
    "ru"    to "Русский",
    "zh-cn" to "中文(简体)",
    "zh-tw" to "中文(繁體)",
    "ja"    to "日本語",
    "ko"    to "한국어",
    "pt"    to "Português",
    "pt-br" to "Português (BR)",
    "it"    to "Italiano",
    "tr"    to "Türkçe",
    "nl"    to "Nederlands",
    "pl"    to "Polski",
    "uk"    to "Українська",
    "fa"    to "فارسی",
    "hi"    to "हिन्दी",
    "id"    to "Indonesia",
    "vi"    to "Tiếng Việt",
    "th"    to "ภาษาไทย",
    "sv"    to "Svenska",
    "no"    to "Norsk",
    "da"    to "Dansk",
    "fi"    to "Suomi",
    "ro"    to "Română",
    "cs"    to "Čeština",
    "hu"    to "Magyar",
    "el"    to "Ελληνικά",
    "bg"    to "Български",
    "hr"    to "Hrvatski",
    "sk"    to "Slovenčina",
    "sr"    to "Srpski",
    "sl"    to "Slovenščina",
    "ca"    to "Català",
    "ms"    to "Melayu",
    "bn"    to "বাংলা",
    "ta"    to "தமிழ்",
    "ml"    to "Malayalam"
)
